#################################################################################
#################################################################################
# Title: RNAScope-Ancestry and ADMIXTURE Comparison				
# Author: Rashi Verma								
# Date: 2026-08-02								
# Description:									
#   - Compare ancestry estimates generated by RNAScope-Ancestry and ADMIXTURE	
#   - Evaluate concordance between ancestry estimation approaches		
#   - Generate correlation and comparison plots					
#										
# Input:									
#   - RNAScope-Ancestry estimates						
#   - ADMIXTURE ancestry estimates						
#										
# Output:									
#   - Concordance statistics							
#   - Comparison plots								
#################################################################################
#################################################################################

library(readxl)
library(ggplot2)

adm <- read_excel("merged_10.3.xlsx")
meca <- read.table("visit_1-20.3.Q", header=TRUE)

labels <- read.table("update_ids_m.txt", header=FALSE)
meca$Population <- labels$V3

dat <- merge(adm,meca,by="Population",suffixes=c("_ADM","_MECA"))
head(dat)

## correlation
Afr_cor <- cor.test(dat$African_ADM,
         dat$African_MECA,
         method="pearson")
Eur_cor <- cor.test(dat$European_ADM,
                    dat$European_MECA,
                    method="pearson")
Amr_cor <- cor.test(dat$American_ADM,
                    dat$American_MECA,
                    method="pearson")

##Mean Absolute Difference (MAD)
Afr_mad <- mean(abs(dat$African_ADM -
           dat$African_MECA))

Eur_mad <- mean(abs(dat$European_ADM -
           dat$European_MECA))


Amr_mad <- mean(abs(dat$American_ADM -
                      dat$American_MECA))

#Scatterplot
Afr <- ggplot(dat,
       aes(African_ADM,
           African_MECA))+
  
  geom_point(size=3)+
  
  geom_smooth(method="lm",
              se=FALSE,
              color="red")+
  
  theme_classic()+
  
  labs(x="ADMIXTURE",
       y="Our pipeline",
       title="African ancestry")
print(Afr)

Eur <- ggplot(dat,
       aes(European_ADM,
           European_MECA))+
  
  geom_point(size=3)+
  
  geom_smooth(method="lm",
              se=FALSE,
              color="blue")+
  
  theme_classic()+
  
  labs(x="ADMIXTURE",
       y="Our pipeline",
       title="European ancestry")
print(Eur)

Amr <- ggplot(dat,
       aes(American_ADM,
           American_MECA))+
  
  geom_point(size=3)+
  
  geom_smooth(method="lm",
              se=FALSE,
              color="darkgreen")+
  
  theme_classic()+
  
  labs(x="ADMIXTURE",
       y="Our pipeline",
       title="American ancestry")
print(Amr)

# Calculate R2
summary(lm(African_MECA~African_ADM,data=dat))
cor(dat$African_ADM, dat$African_MECA)^2

summary(lm(European_MECA~European_ADM,data=dat))
cor(dat$European_ADM, dat$European_MECA)^2

summary(lm(American_MECA~American_ADM,data=dat))
cor(dat$American_ADM, dat$American_MECA)^2

###################################################################################

# for meca samples only
library(readxl)
library(ggplot2)
library(dplyr)

#  READ DATA
# ADMIXTURE ancestry proportions
adm <- read_excel("merged_10.3.xlsx")

# RNAScope-Ancestry ancestry proportions
meca <- read.table(
  "visit_1-20.3.Q",
  header = TRUE
)

# Population/sample labels
labels <- read.table(
  "update_ids_m.txt",
  header = FALSE
)

# Add population IDs to RNAScope-Ancestry results
meca$Population <- labels$V3


# MERGE ADMIXTURE AND RNASCOPE-ANCESTRY RESULTS
dat <- merge(
  adm,
  meca,
  by = "Population",
  suffixes = c("_ADM", "_MECA")
)

# Check merged data
head(dat)

# Number of samples in merged dataset
nrow(dat)


# IDENTIFY MECA QUERY SAMPLES
# MECA query samples are AFR1–AFR490
dat_query <- dat[
  grepl("^AFR[0-9]+$", dat$Population),
]

# Check number of MECA samples
length(unique(dat_query$Population))

# Check IDs
head(dat_query$Population)
tail(dat_query$Population)


# FUNCTION TO CALCULATE METRICS
calculate_metrics <- function(data, ancestry) {
  
  adm_col  <- paste0(ancestry, "_ADM")
  meca_col <- paste0(ancestry, "_MECA")
  
  # Pearson correlation
  cor_test <- cor.test(
    data[[adm_col]],
    data[[meca_col]],
    method = "pearson"
  )
  
  # Pearson r
  r <- unname(cor_test$estimate)
  
  # R-squared
  r2 <- r^2
  
  # P-value
  p_value <- cor_test$p.value
  
  # Mean Absolute Difference
  mad <- mean(
    abs(data[[adm_col]] - data[[meca_col]]),
    na.rm = TRUE
  )
  
  data.frame(
    Ancestry = ancestry,
    N = nrow(data),
    Pearson_r = r,
    R2 = r2,
    P_value = p_value,
    MAD = mad
  )
}


# METRICS — ALL SAMPLES
metrics_all <- bind_rows(
  calculate_metrics(dat, "African"),
  calculate_metrics(dat, "European"),
  calculate_metrics(dat, "American")
)

metrics_all


# METRICS — MECA QUERY SAMPLES ONLY
metrics_query <- bind_rows(
  calculate_metrics(dat_query, "African"),
  calculate_metrics(dat_query, "European"),
  calculate_metrics(dat_query, "American")
)

metrics_query


# COMBINE METRICS
metrics_all$Dataset <- "All samples"
metrics_query$Dataset <- "MECA query only"

metrics_combined <- bind_rows(
  metrics_all,
  metrics_query
) %>%
  select(
    Dataset,
    Ancestry,
    N,
    Pearson_r,
    R2,
    P_value,
    MAD
  )

metrics_combined


# AFRICAN ANCESTRY — MECA QUERY ONLY
Afr_query <- ggplot(
  dat_query,
  aes(
    x = African_ADM,
    y = African_MECA
  )
) +
  geom_point(size = 3) +
  geom_smooth(
    method = "lm",
    se = FALSE,
    color = "red"
  ) +
  theme_classic() +
  labs(
    x = "ADMIXTURE African ancestry",
    y = "RNAScope-Ancestry African ancestry",
    title = "African ancestry — MECA query samples"
  )

print(Afr_query)


# EUROPEAN ANCESTRY — MECA QUERY ONLY
Eur_query <- ggplot(
  dat_query,
  aes(
    x = European_ADM,
    y = European_MECA
  )
) +
  geom_point(size = 3) +
  geom_smooth(
    method = "lm",
    se = FALSE,
    color = "blue"
  ) +
  theme_classic() +
  labs(
    x = "ADMIXTURE European ancestry",
    y = "RNAScope-Ancestry European ancestry",
    title = "European ancestry — MECA query samples"
  )

print(Eur_query)


# AMERICAN ANCESTRY — MECA QUERY ONLY
Amr_query <- ggplot(
  dat_query,
  aes(
    x = American_ADM,
    y = American_MECA
  )
) +
  geom_point(size = 3) +
  geom_smooth(
    method = "lm",
    se = FALSE,
    color = "darkgreen"
  ) +
  theme_classic() +
  labs(
    x = "ADMIXTURE American ancestry",
    y = "RNAScope-Ancestry American ancestry",
    title = "American ancestry — MECA query samples"
  )

print(Amr_query)


# OPTIONAL: ADD R AND R² TO THE QUERY PLOTS
# Function to extract r and R2
get_annotation <- function(data, ancestry) {
  
  adm_col  <- paste0(ancestry, "_ADM")
  meca_col <- paste0(ancestry, "_MECA")
  
  r <- cor(
    data[[adm_col]],
    data[[meca_col]],
    use = "complete.obs",
    method = "pearson"
  )
  
  r2 <- r^2
  
  paste0(
    "r = ", round(r, 3),
    "\nR² = ", round(r2, 3)
  )
}


Afr_label <- get_annotation(dat_query, "African")
Eur_label <- get_annotation(dat_query, "European")
Amr_label <- get_annotation(dat_query, "American")


# African
Afr_query +
  annotate(
    "text",
    x = Inf,
    y = -Inf,
    label = Afr_label,
    hjust = 1.1,
    vjust = -0.5,
    size = 5
  )


# European
Eur_query +
  annotate(
    "text",
    x = Inf,
    y = -Inf,
    label = Eur_label,
    hjust = 1.1,
    vjust = -0.5,
    size = 5
  )


# American
Amr_query +
  annotate(
    "text",
    x = Inf,
    y = -Inf,
    label = Amr_label,
    hjust = 1.1,
    vjust = -0.5,
    size = 5
  )


# SAVE RESULTS
write.csv(
  metrics_combined,
  "ADMIXTURE_vs_RNAScope_ancestry_benchmarking.csv",
  row.names = FALSE
)

# LINEAR REGRESSION SUMMARY — MECA QUERY ONLY
get_regression_summary <- function(data, ancestry) {
  
  adm_col  <- paste0(ancestry, "_ADM")
  meca_col <- paste0(ancestry, "_MECA")
  
  # Linear regression:
  # RNAScope-Ancestry = intercept + slope * ADMIXTURE
  model <- lm(
    data[[meca_col]] ~ data[[adm_col]],
    data = data
  )
  
  model_summary <- summary(model)
  
  # Extract coefficients
  intercept <- coef(model)[1]
  slope <- coef(model)[2]
  
  # R-squared
  r2 <- model_summary$r.squared
  
  # P-value for slope
  p_value <- coef(model_summary)[2, 4]
  
  # Pearson correlation
  r <- cor(
    data[[adm_col]],
    data[[meca_col]],
    use = "complete.obs",
    method = "pearson"
  )
  
  # Mean Absolute Difference
  mad <- mean(
    abs(data[[adm_col]] - data[[meca_col]]),
    na.rm = TRUE
  )
  
  data.frame(
    Dataset = "MECA query only",
    Ancestry = ancestry,
    N = nrow(data),
    Pearson_r = r,
    R2 = r2,
    P_value = p_value,
    MAD = mad,
    Intercept = intercept,
    Slope = slope,
    Equation = paste0(
      "Y = ",
      round(intercept, 5),
      " + ",
      round(slope, 5),
      "X"
    )
  )
}


# Calculate regression summaries
regression_query <- bind_rows(
  get_regression_summary(dat_query, "African"),
  get_regression_summary(dat_query, "European"),
  get_regression_summary(dat_query, "American")
)

regression_query